package jp.igapyon.mikureadfile.cli;

public final class HelpText {
    private HelpText() {
    }

    public static String helpText() {
        return "miku-readfile\n"
                + "\n"
                + "Local-first structured file reader CLI for AI agents and automation.\n"
                + "\n"
                + "Usage:\n"
                + "  miku-readfile < request.json > result.json\n"
                + "  miku-readfile --version\n"
                + "  miku-readfile --help\n"
                + "  miku-readfile -h\n"
                + "\n"
                + "Primary contract:\n"
                + "  stdin   request JSON\n"
                + "  stdout  result JSON\n"
                + "  stderr  unexpected runtime-level messages only\n"
                + "\n"
                + "Minimal request:\n"
                + "{\n"
                + "  \"version\": 1,\n"
                + "  \"root\": \".\",\n"
                + "  \"files\": [\"README.md\"]\n"
                + "}\n"
                + "\n"
                + "Range request example:\n"
                + "{\n"
                + "  \"version\": 1,\n"
                + "  \"root\": \".\",\n"
                + "  \"files\": [\n"
                + "    {\n"
                + "      \"path\": \"src/Legacy.java\",\n"
                + "      \"range\": {\n"
                + "        \"startLine\": 120,\n"
                + "        \"lineCount\": 40\n"
                + "      }\n"
                + "    }\n"
                + "  ],\n"
                + "  \"encoding\": {\n"
                + "    \"default\": \"utf-8\",\n"
                + "    \"extensions\": {\n"
                + "      \".java\": \"shift_jis\"\n"
                + "    }\n"
                + "  }\n"
                + "}\n"
                + "\n"
                + "Safety:\n"
                + "  files must be request.root-relative paths using /\n"
                + "  absolute paths and .. path segments are validation errors\n"
                + "  filesystem root and user home are rejected as too broad\n"
                + "  directories, symlinks, binary files, decode errors, and oversized files are skipped\n"
                + "\n"
                + "Exit codes:\n"
                + "  0  ok: true\n"
                + "  1  ok: false expected failure\n"
                + "  2  malformed stdin or invalid CLI usage\n"
                + "  3  unexpected runtime error\n";
    }
}
